### PR TITLE
Port iOS API, sample, test to Unified API

### PR DESCRIPTION
**Pull request by kochizufan**
I try to port iOS API, sample, test to Unified API version.

### CODE REVIEW

**Comment by xivk** [comment]
Thanks again for the work.

It looks like there are new projects for unified API. What would be the minimum change required? In other words, did you have to change any actual code or was it just configuration/project setup?

I would like to update this in the existing projects.

**Comment by xivk** [comment]
Does this look right:

https://github.com/JoeCooper/OsmSharp/commit/99ab45bbb37de3e04c715034ee47b4edf16bca42

**Comment by kochizufan** [comment]
Sorry for replying so late.

I add new project for Unified API, but just because for keeping Classic API project.
Unified API and Classic API cannot contain one project, and if I migrate Classic API project to Unified one, we lost Classic API version of OsmSharp.
So I add new project for Unified API.

What I do is just 

* Add project for Unified API
* Add cs files to Unified API project from Classic API project by linking
* Add context switch for Added cs file to change namespace of Monotouch/Xamarin.iOS APIs
* Add some cast to nint <=> int, nfloat <=> float or so.

and then we have both Classic/Unified version of OsmSharp.dll.

**Comment by xivk** [comment]
Ok, need to update my build-server. Thanks for the effort again!

**Pull request merged**
